version: 2.1
jobs:
  build-and-test:
    docker:
      - image: maven:3.9-eclipse-temurin-17
    steps:
      - checkout
      - run:
          name: Run Tests
          command: mvn -B verify
      - store_test_results:
          path: target/surefire-reports
workflows:
  main-workflow:
    jobs:
      - build-and-test