version: 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Run Maven Build & Tests
          command: mvn -B verify

workflows:
  main-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main