version: 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Start Test Environment
          command: docker-compose -f docker-compose.ci.yml up -d
      - run:
          name: Wait for Services
          command: |
            echo "Waiting for Kafka..."
            while ! docker exec kafka kafka-topics --bootstrap-server localhost:9092 --list; do
              sleep 5
            done
            echo "Kafka is up!"
      - run:
          name: Run Maven Tests
          command: mvn -B verify -Dspring.profiles.active=ci
      - store_test_results:
          path: target/surefire-reports
workflows:
  main-workflow:
    jobs:
      - build-and-test