version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Run Maven Build & Tests
          command: mvn -B verify
      - store_test_results:
          path: target/surefire-reports

workflows:
  main-workflow:
    jobs:
      - build-and-test