apiVersion: v1
kind: Service
metadata:
  name: ebanking-portal-service
spec:
  type: ClusterIP
  selector:
    app: ebanking-portal-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080